### ISSUE TITLE
have error in Build libpng for Android

### ISSUE THREAD

**Issue by kendgin** [WanghongLin/miscellaneous#1]
have error when i try Build libpng for Android 

3rdparty/libpng/CMakeFiles/libpng.dir/build.make:446: recipe for target '3rdparty/libpng/CMakeFiles/libpng.dir/arm/filter_neon.S.o' failed
make[2]: *** [3rdparty/libpng/CMakeFiles/libpng.dir/arm/filter_neon.S.o] Error 1
CMakeFiles/Makefile2:655: recipe for target '3rdparty/libpng/CMakeFiles/libpng.dir/all' failed
make[1]: *** [3rdparty/libpng/CMakeFiles/libpng.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by WanghongLin** [comment]
I can not replicate your error in my environment with libpng-1.6.37.tar.xz, what's your libpng version?

Only got warning when do the configuration, but it's harmless.

>configure: WARNING: --enable-arm-neon: please specify 'check' or 'api', if
            you want the optimizations unconditionally pass -mfpu=neon
            to the compiler

**Comment by kendgin** [comment]
thank you for your reply
your demo heif for android only support armeabi-v7a , can we do somthing else then the demo support armeabi、arm64-v8a、mips、x86 ?

**Comment by WanghongLin** [comment]
Other ABIs except `armeabi-v7a` will be provided in the future.

If you need right now, try to create your own version. For your target architecture, first create a standalone toolchain from android ndk, e.g `arm64-v8a`

```sh
$ ./make_standalone_toolchain.py --arch arm64 --api 21 --stl libc++ --force --install-dir /tmp/ndkarm64
```

Then follow the same step to build each library with some minor changes, `CC` should be `/tmp/ndkarm64/bin/aarch64-linux-android-clang` and `CXX` should be `/tmp/ndkarm64/bin/aarch64-linux-android-clang++` for C++ code, and `arm-linux-androideabi` should replaced by `aarch64-linux-android`.

Below is an example to build `libpng` for `arm64-v8a`
```sh
$ export CC=/tmp/ndkarm64/bin/aarch64-linux-android-clang CFLAGS='-fPIE' LDFLAGS='-pie -fPIE' PATH=$PATH:/tmp/ndkarm64/bin
$ ./configure --prefix=/tmp/out/libpngaarch64 --enable-shared=no --enable-arm-neon --host=aarch64-linux-android
$ make -j8 && make install
```

**Comment by WanghongLin** [comment]
`arm64-v8a`, `x86` and `x86_64` was added, see
https://github.com/WanghongLin/HeifAndroid/commit/870679b7df9a17cb401a63591b6722146b7f9d6a

https://github.com/WanghongLin/HeifAndroid/commit/0522bcf31639f8d305d0f19b781319159eaa7973

https://github.com/WanghongLin/HeifAndroid/commit/85e3dc9960b5beec331c05b49c6a42af31526246
