### ISSUE TITLE
error in Build libpng for Android

### ISSUE THREAD

**Issue by kendgin** [WanghongLin/miscellaneous#2]
error in Build libpng for Android

depbase=`echo contrib/tools/png-fix-itxt.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	/tmp/ndk/bin/arm-linux-androideabi-clang -DHAVE_CONFIG_H -I.     -fPIE -MT contrib/tools/png-fix-itxt.o -MD -MP -MF $depbase.Tpo -c -o contrib/tools/png-fix-itxt.o contrib/tools/png-fix-itxt.c &&\
	mv -f $depbase.Tpo $depbase.Po
make[1]: *** [arm/filter_neon.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2

**Comment by WanghongLin** [comment]
#1 duplication
